### ISSUE TITLE
DiscoverInterface not in go package

### ISSUE THREAD

**Issue by bachittle** [jackpal/gateway#26]
# Expected
- get your code from https://pkg.go.dev/github.com/jackpal/gateway using go get
- try to use the exported function DiscoverInterface

# What I got
- DiscoverInterface not defined in gateway

# How to fix
- ### FOR THE USER
- clone the repository into your project (I did it under ext/gateway for my project https://github.com/bachittle/ping-go)
- route your go.mod to the local repository using 'replace' function
![image](https://user-images.githubusercontent.com/39804642/100522882-126f7e80-317a-11eb-8e8b-5c41e5a1d3ee.png)
- ### FOR THE OWNER
- keep https://pkg.go.dev/github.com/jackpal/gateway up to date with this repository.
- If you are the owner, then update the goproxy, if not then contact the real owner

**Comment by bachittle** [comment]
So I believe all you have to do is create a new 'version' in github releases. If you could do that, that would be great.

**Comment by jackpal** [comment]
Sorry about that. I tagged the current HEAD v1.0.7
