### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [jackpal/gateway#4]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for gateway and versioning would help Debian keep up with development.

**Comment by jackpal** [comment]
Good point. I have to think a bit about how to do this.

**Comment by jackpal** [comment]
I used git tag -a to tag the head as v1.0 -- please let me know if that's not what you were asking for.

**Comment by aviau** [comment]
Yep! This is what I expected.

As development continues, please keep tagging respecting http://semver.org/
