### ISSUE TITLE
No longer compiles with older Go versions

### ISSUE THREAD

**Issue by jech** [jackpal/gateway#41]
```
$ /usr/lib/go-1.19/bin/go build
gateway_parsers.go:14:2: package slices is not in GOROOT (/usr/lib/go-1.19/src/slices)
```

**Comment by jackpal** [comment]
This is intentional. I guess you could use an earlier version of the library if for some reason you want to use an older version of golang.

**Comment by jackpal** [comment]
Reopening. I should change the go.mod file to document this golang version requirement.

**Comment by jech** [comment]
> I guess you could use an earlier version of the library

That's what I'm doing.

> if for some reason you want to use an older version of golang.

I'm using the latest version, but I don't want to force my users to do so without good reason.

**Comment by jackpal** [comment]
Regarding my earlier comment:

> Reopening. I should change the go.mod file to document this golang version requirement.

Actually the go.mod file already specifies golang 1.21, so it doesn't need to be updated.

I guess there's nothing more to do on this issue.
